/**
 * Word Data Import Types
 * Used exclusively for JSON data files import (prisma/seed.ts)
 *
 * Note: These types match the structure of JSON files in data/words/
 * They may contain fields that are not stored in the database (e.g., frequency, difficulty)
 */

/**
 * Example sentence structure in JSON files
 */
export interface WordExampleJson {
  id: string;
  english: string;
  japanese: string;
  difficulty?: number; // Optional - not used in current schema
  context?: string; // Optional - not used in current schema
}

/**
 * Word data structure in JSON files
 */
export interface WordDataJson {
  id?: string; // Optional - auto-generated by Prisma
  english: string;
  japanese: string;
  phonetic?: string; // IPA notation
  partOfSpeech: string; // noun, verb, adjective, etc.
  frequency?: number; // Optional - not used in current schema
  examples: WordExampleJson[]; // First example will be used
}

/**
 * Word data file structure
 */
export interface WordDataFile {
  words: WordDataJson[];
  difficulty?: 'easy' | 'medium' | 'hard'; // Optional - for organization only
  fileNumber?: number; // Optional - for organization only
}

// Available word data files (for reference)
export const WORD_DATA_FILES = {
  easy: ['easy1'],
  medium: ['medium1'],
  hard: ['hard1']
} as const;